/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.systemui.monet

import android.content.theming.ThemeStyle
import android.graphics.Color
import android.util.Log
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.filters.SmallTest
import androidx.test.platform.app.InstrumentationRegistry
import com.android.systemui.monet.ColorScheme.GOOGLE_BLUE
import com.google.ux.material.libmonet.dynamiccolor.ColorSpec.SpecVersion
import com.google.ux.material.libmonet.dynamiccolor.DynamicScheme.Platform
import com.google.ux.material.libmonet.hct.Hct
import com.google.ux.material.libmonet.scheme.SchemeTonalSpot
import java.io.File
import java.io.FileWriter
import java.io.StringWriter
import javax.xml.parsers.DocumentBuilderFactory
import javax.xml.transform.OutputKeys
import javax.xml.transform.TransformerException
import javax.xml.transform.TransformerFactory
import javax.xml.transform.dom.DOMSource
import javax.xml.transform.stream.StreamResult
import kotlin.math.abs
import org.junit.Test
import org.junit.runner.RunWith
import org.w3c.dom.Document
import org.w3c.dom.Element
import org.w3c.dom.Node

private const val CONTRAST = 0.0

private const val fileHeader =
    """
  ~ Copyright (C) 2022 The Android Open Source Project
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
"""

private fun testName(name: String): String {
    return "Auto generated by: atest ColorSchemeTest#$name"
}

private const val commentRoles =
    "Colors used in Android system, from design system. These " +
        "values can be overlaid at runtime by OverlayManager RROs."

private const val commentOverlay = "This value can be overlaid at runtime by OverlayManager RROs."

private fun commentWhite(paletteName: String): String {
    return "Lightest shade of the $paletteName color used by the system. White. $commentOverlay"
}

private fun commentBlack(paletteName: String): String {
    return "Darkest shade of the $paletteName color used by the system. Black. $commentOverlay"
}

private fun commentShade(paletteName: String, tone: Int): String {
    return "Shade of the $paletteName system color at $tone% perceptual luminance (L* in L*a*b* " +
        "color space). $commentOverlay"
}

@SmallTest
@RunWith(AndroidJUnit4::class)
class ColorSchemeTest {
    private val paletteTokens =
        DynamicColors.getAllAccentPalette() +
            DynamicColors.getAllNeutralPalette() +
            DynamicColors.getAllErrorPalette()

    @Test
    fun generateThemeStyles() {
        val document = buildDoc<Any>()

        val themes = document.createElement("themes")
        document.appendWithBreak(themes)

        for (isDarkMode in arrayOf(true, false)) {
            val mode = document.createElement("mode")
            mode.setAttribute("type", if (isDarkMode) "dark" else "light")
            themes.appendChild(mode)

            var hue = 0.0
            while (hue < 360) {
                val sourceColorHct = Hct.from(hue, 50.0, 50.0)
                val sourceColorInt = sourceColorHct.toInt()
                val sourceColor = Color.valueOf(sourceColorInt)
                val sourceColorHex = "#" + sourceColorInt.toRGBHex()

                val theme = document.createElement("theme")
                theme.setAttribute("color", sourceColorHex)
                mode.appendChild(theme)

                for (styleValue in ThemeStyle.values()) {
                    if (
                        styleValue == ThemeStyle.CLOCK ||
                            styleValue == ThemeStyle.CLOCK_VIBRANT ||
                            styleValue == ThemeStyle.CONTENT
                    ) {
                        continue
                    }

                    val style = document.createElement(ThemeStyle.name(styleValue).lowercase())
                    val colorScheme =
                        ColorScheme(
                            listOf(sourceColor.toArgb()),
                            isDarkMode,
                            styleValue,
                            0.0,
                            SpecVersion.SPEC_2026,
                            Platform.PHONE,
                        )

                    style.appendChild(
                        document.createTextNode(
                            listOf(
                                    colorScheme.accent1,
                                    colorScheme.accent2,
                                    colorScheme.accent3,
                                    colorScheme.neutral1,
                                    colorScheme.neutral2,
                                )
                                .flatMap { a -> listOf(*a.allShades.toTypedArray()) }
                                .joinToString(",", transform = Int::toRGBHex)
                        )
                    )
                    theme.appendChild(style)
                }

                hue += 60
            }
        }

        saveFile(document, "themes.xml")
    }

    @Test
    fun generateDefaultValues() {
        val document = buildDoc<Any>()

        val resources = document.createElement("resources")
        document.appendWithBreak(resources)

        // shade colors
        arrayOf(false, true).forEach { isDark ->
            val suffix = if (isDark) "_dark" else "_light"
            val dynamicScheme = SchemeTonalSpot(Hct.fromInt(GOOGLE_BLUE), isDark, CONTRAST)
            (paletteTokens).forEach {
                val paletteName =
                    when (it.first.substringBefore("_")) {
                        "accent1" -> "Primary"
                        "accent2" -> "Secondary"
                        "accent3" -> "Tertiary"
                        "neutral1" -> "Neutral"
                        "neutral2" -> "Neutral Variant"
                        else -> "Error"
                    }

                val shade = it.first.substringAfter("_").toInt()

                val comment =
                    when (shade) {
                        0 -> commentWhite(paletteName)
                        1000 -> commentBlack(paletteName)
                        else -> commentShade(paletteName, abs(shade / 10 - 100))
                    }

                resources.createColorEntry(
                    "system_${it.first}$suffix",
                    it.second.getArgb(dynamicScheme),
                    comment,
                )
            }
        }

        // dynamic colors
        arrayOf(false, true).forEach { isDark ->
            val suffix = if (isDark) "_dark" else "_light"
            val dynamicScheme = SchemeTonalSpot(Hct.fromInt(GOOGLE_BLUE), isDark, CONTRAST)
            (DynamicColors.getAllDynamicColorsMapped() + DynamicColors.getFixedColorsMapped())
                .forEach {
                    resources.createColorEntry(
                        "system_${it.first}$suffix",
                        it.second.getArgb(dynamicScheme),
                    )
                }
        }

        // custom colors
        arrayOf(false, true).forEach { isDark ->
            val suffix = if (isDark) "_dark" else "_light"
            val dynamicScheme = SchemeTonalSpot(Hct.fromInt(GOOGLE_BLUE), isDark, CONTRAST)
            DynamicColors.getCustomColorsMapped().forEach {
                resources.createColorEntry(
                    "system_${it.first}$suffix",
                    it.second.getArgb(dynamicScheme),
                )
            }
        }

        saveFile(document, "colors.xml")
    }

    @Test
    fun generateSymbols() {
        val document = buildDoc<Any>()

        val resources = document.createElement("resources")
        document.appendWithBreak(resources)

        arrayOf(false, true).forEach { isDark ->
            val suffix = if (isDark) "_dark" else "_light"

            (paletteTokens).forEach {
                val newName = "system_" + it.first + suffix // keep snake_case

                resources.createEntry(
                    "java-symbol",
                    arrayOf(Pair("name", newName), Pair("type", "color")),
                    null,
                )
            }
        }

        (DynamicColors.getAllDynamicColorsMapped() + DynamicColors.getFixedColorsMapped()).forEach {
            val newName = ("material_color_" + it.first).snakeToLowerCamelCase()

            resources.createEntry(
                "java-symbol",
                arrayOf(Pair("name", newName), Pair("type", "color")),
                null,
            )
        }

        DynamicColors.getCustomColorsMapped().forEach {
            val newName = ("custom_color_" + it.first).snakeToLowerCamelCase()

            resources.createEntry(
                "java-symbol",
                arrayOf(Pair("name", newName), Pair("type", "color")),
                null,
            )
        }

        arrayOf("_light", "_dark").forEach { suffix ->
            DynamicColors.getCustomColorsMapped().forEach {
                val newName = "system_" + it.first + suffix

                resources.createEntry(
                    "java-symbol",
                    arrayOf(Pair("name", newName), Pair("type", "color")),
                    null,
                )
            }
        }

        saveFile(document, "symbols.xml")
    }

    @Test
    fun generateDynamicColors() {
        arrayOf(false, true).forEach { isDark ->
            val document = buildDoc<Any>()

            val resources = document.createElement("resources")
            document.appendWithBreak(resources)

            val suffix = if (isDark) "_dark" else "_light"

            (paletteTokens).forEach {
                val newName = ("system_" + it.first) // keep snake_case
                val colorValue = "@color/" + newName + suffix

                resources.createColorEntry(newName, colorValue)
            }

            (DynamicColors.getAllDynamicColorsMapped() + DynamicColors.getFixedColorsMapped())
                .forEach {
                    val newName = ("material_color_" + it.first).snakeToLowerCamelCase()
                    val colorValue = "@color/system_" + it.first + suffix

                    resources.createColorEntry(newName, colorValue)
                }

            DynamicColors.getCustomColorsMapped().forEach {
                val newName = ("custom_color_" + it.first).snakeToLowerCamelCase()
                resources.createColorEntry(newName, "@color/system_" + it.first + suffix)
            }

            saveFile(document, "colors_dynamic_$suffix.xml")
        }
    }

    @Test
    fun generatePublic() {
        val document = buildDoc<Any>()

        val resources = document.createElement("resources")
        val group = document.createElement("staging-public-group")

        resources.appendChild(group)
        document.appendWithBreak(resources)

        val rClass = com.android.internal.R.color::class.java
        val existingFields = rClass.declaredFields.map { it.name }.toSet()

        arrayOf("_light", "_dark").forEach { suffix ->
            (DynamicColors.getAllDynamicColorsMapped() + DynamicColors.getFixedColorsMapped())
                .forEach {
                    val name = "system_" + it.first + suffix
                    if (!existingFields.contains(name)) {
                        group.createEntry("public", arrayOf(Pair("name", name)), null)
                    }
                }
        }

        saveFile(document, "public.xml")
    }

    // Helper Functions

    private inline fun <reified T> buildDoc(): Document {
        val functionName = T::class.simpleName + ""
        val factory = DocumentBuilderFactory.newInstance()
        val builder = factory.newDocumentBuilder()
        val document = builder.newDocument()

        document.appendWithBreak(document.createComment(fileHeader))
        document.appendWithBreak(document.createComment(testName(functionName)))

        return document
    }

    private fun documentToString(document: Document): String {
        try {
            val transformerFactory = TransformerFactory.newInstance()
            val transformer = transformerFactory.newTransformer()
            transformer.setOutputProperty(OutputKeys.MEDIA_TYPE, "application/xml")
            transformer.setOutputProperty(OutputKeys.METHOD, "xml")
            transformer.setOutputProperty(OutputKeys.INDENT, "yes")
            transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "4")

            val stringWriter = StringWriter()
            transformer.transform(DOMSource(document), StreamResult(stringWriter))
            return stringWriter.toString()
        } catch (e: TransformerException) {
            throw RuntimeException("Error transforming XML", e)
        }
    }

    private fun saveFile(document: Document, fileName: String) {
        val context = InstrumentationRegistry.getInstrumentation().context
        val outPath = context.filesDir.path + "/" + fileName
        Log.d("ColorSchemeXml", "Artifact $fileName created")
        val writer = FileWriter(File(outPath))
        writer.write(documentToString(document))
        writer.close()
    }
}

private fun Element.createColorEntry(name: String, value: Int, comment: String? = null) {
    this.createColorEntry(name, "#" + value.toRGBHex(), comment)
}

private fun Element.createColorEntry(name: String, value: String, comment: String? = null) {
    this.createEntry("color", arrayOf(Pair("name", name)), value, comment)
}

private fun Element.createEntry(
    tagName: String,
    attrs: Array<Pair<String, String>>,
    value: String?,
    comment: String? = null,
) {
    val doc = this.ownerDocument

    if (comment != null) {
        this.appendChild(doc.createComment(comment))
    }

    val child = doc.createElement(tagName)
    this.appendChild(child)

    attrs.forEach { child.setAttribute(it.first, it.second) }

    if (value !== null) {
        child.appendChild(doc.createTextNode(value))
    }
}

private fun Node.appendWithBreak(child: Node, lineBreaks: Int = 1): Node {
    val doc = if (this is Document) this else this.ownerDocument
    val node = doc.createTextNode("\n".repeat(lineBreaks))
    this.appendChild(node)
    return this.appendChild(child)
}

private fun Int.toRGBHex(): String {
    return "%06X".format(0xFFFFFF and this)
}

private fun String.snakeToLowerCamelCase(): String {
    val pattern = "_[a-z]".toRegex()
    return replace(pattern) { it.value.last().uppercase() }
}
